//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miiCard.Consumers.Service.v1.Financial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfFinancialRefreshStatus", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfFinancialRefreshStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialRefreshStatus DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialRefreshStatus Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialRefreshStatus", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class FinancialRefreshStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.RefreshState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.RefreshState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefreshState", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    public enum RefreshState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataAvailable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfMiiFinancialData", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfMiiFinancialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.MiiFinancialData DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.MiiFinancialData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiFinancialData", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class MiiFinancialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialProvider[] FinancialProvidersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialProvider[] FinancialProviders {
            get {
                return this.FinancialProvidersField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialProvidersField, value) != true)) {
                    this.FinancialProvidersField = value;
                    this.RaisePropertyChanged("FinancialProviders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialProvider", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class FinancialProvider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialAccount[] FinancialAccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialCreditCard[] FinancialCreditCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialAccount[] FinancialAccounts {
            get {
                return this.FinancialAccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialAccountsField, value) != true)) {
                    this.FinancialAccountsField = value;
                    this.RaisePropertyChanged("FinancialAccounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialCreditCard[] FinancialCreditCards {
            get {
                return this.FinancialCreditCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialCreditCardsField, value) != true)) {
                    this.FinancialCreditCardsField = value;
                    this.RaisePropertyChanged("FinancialCreditCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialAccount", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class FinancialAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditsSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyIsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DebitsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DebitsSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialTransaction[] TransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingBalance {
            get {
                return this.ClosingBalanceField;
            }
            set {
                if ((this.ClosingBalanceField.Equals(value) != true)) {
                    this.ClosingBalanceField = value;
                    this.RaisePropertyChanged("ClosingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditsCount {
            get {
                return this.CreditsCountField;
            }
            set {
                if ((this.CreditsCountField.Equals(value) != true)) {
                    this.CreditsCountField = value;
                    this.RaisePropertyChanged("CreditsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditsSum {
            get {
                return this.CreditsSumField;
            }
            set {
                if ((this.CreditsSumField.Equals(value) != true)) {
                    this.CreditsSumField = value;
                    this.RaisePropertyChanged("CreditsSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyIso {
            get {
                return this.CurrencyIsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIsoField, value) != true)) {
                    this.CurrencyIsoField = value;
                    this.RaisePropertyChanged("CurrencyIso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DebitsCount {
            get {
                return this.DebitsCountField;
            }
            set {
                if ((this.DebitsCountField.Equals(value) != true)) {
                    this.DebitsCountField = value;
                    this.RaisePropertyChanged("DebitsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DebitsSum {
            get {
                return this.DebitsSumField;
            }
            set {
                if ((this.DebitsSumField.Equals(value) != true)) {
                    this.DebitsSumField = value;
                    this.RaisePropertyChanged("DebitsSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder {
            get {
                return this.HolderField;
            }
            set {
                if ((object.ReferenceEquals(this.HolderField, value) != true)) {
                    this.HolderField = value;
                    this.RaisePropertyChanged("Holder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedUtc {
            get {
                return this.LastUpdatedUtcField;
            }
            set {
                if ((this.LastUpdatedUtcField.Equals(value) != true)) {
                    this.LastUpdatedUtcField = value;
                    this.RaisePropertyChanged("LastUpdatedUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortCode {
            get {
                return this.SortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SortCodeField, value) != true)) {
                    this.SortCodeField = value;
                    this.RaisePropertyChanged("SortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialTransaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialCreditCard", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class FinancialCreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditsSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyIsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DebitsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DebitsSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RunningBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Financial.FinancialTransaction[] TransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((this.CreditLimitField.Equals(value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditsCount {
            get {
                return this.CreditsCountField;
            }
            set {
                if ((this.CreditsCountField.Equals(value) != true)) {
                    this.CreditsCountField = value;
                    this.RaisePropertyChanged("CreditsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditsSum {
            get {
                return this.CreditsSumField;
            }
            set {
                if ((this.CreditsSumField.Equals(value) != true)) {
                    this.CreditsSumField = value;
                    this.RaisePropertyChanged("CreditsSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyIso {
            get {
                return this.CurrencyIsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIsoField, value) != true)) {
                    this.CurrencyIsoField = value;
                    this.RaisePropertyChanged("CurrencyIso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DebitsCount {
            get {
                return this.DebitsCountField;
            }
            set {
                if ((this.DebitsCountField.Equals(value) != true)) {
                    this.DebitsCountField = value;
                    this.RaisePropertyChanged("DebitsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DebitsSum {
            get {
                return this.DebitsSumField;
            }
            set {
                if ((this.DebitsSumField.Equals(value) != true)) {
                    this.DebitsSumField = value;
                    this.RaisePropertyChanged("DebitsSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder {
            get {
                return this.HolderField;
            }
            set {
                if ((object.ReferenceEquals(this.HolderField, value) != true)) {
                    this.HolderField = value;
                    this.RaisePropertyChanged("Holder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedUtc {
            get {
                return this.LastUpdatedUtcField;
            }
            set {
                if ((this.LastUpdatedUtcField.Equals(value) != true)) {
                    this.LastUpdatedUtcField = value;
                    this.RaisePropertyChanged("LastUpdatedUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RunningBalance {
            get {
                return this.RunningBalanceField;
            }
            set {
                if ((this.RunningBalanceField.Equals(value) != true)) {
                    this.RunningBalanceField = value;
                    this.RaisePropertyChanged("RunningBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Financial.FinancialTransaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialTransaction", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Financial")]
    [System.SerializableAttribute()]
    public partial class FinancialTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountCreditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountDebitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AmountCredited {
            get {
                return this.AmountCreditedField;
            }
            set {
                if ((this.AmountCreditedField.Equals(value) != true)) {
                    this.AmountCreditedField = value;
                    this.RaisePropertyChanged("AmountCredited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AmountDebited {
            get {
                return this.AmountDebitedField;
            }
            set {
                if ((this.AmountDebitedField.Equals(value) != true)) {
                    this.AmountDebitedField = value;
                    this.RaisePropertyChanged("AmountDebited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="v1.Financial.IFinancial")]
    public interface IFinancial {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/IsRefreshInProgress", ReplyAction="http://tempuri.org/IFinancial/IsRefreshInProgressResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsRefreshInProgress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/IsRefreshInProgressCreditCards", ReplyAction="http://tempuri.org/IFinancial/IsRefreshInProgressCreditCardsResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsRefreshInProgressCreditCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/RefreshFinancialData", ReplyAction="http://tempuri.org/IFinancial/RefreshFinancialDataResponse")]
        miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfFinancialRefreshStatus RefreshFinancialData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/RefreshFinancialDataCreditCards", ReplyAction="http://tempuri.org/IFinancial/RefreshFinancialDataCreditCardsResponse")]
        miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfFinancialRefreshStatus RefreshFinancialDataCreditCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/GetFinancialTransactions", ReplyAction="http://tempuri.org/IFinancial/GetFinancialTransactionsResponse")]
        miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfMiiFinancialData GetFinancialTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancial/GetFinancialTransactionsCreditCards", ReplyAction="http://tempuri.org/IFinancial/GetFinancialTransactionsCreditCardsResponse")]
        miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfMiiFinancialData GetFinancialTransactionsCreditCards();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinancialChannel : miiCard.Consumers.Service.v1.Financial.IFinancial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialClient : System.ServiceModel.ClientBase<miiCard.Consumers.Service.v1.Financial.IFinancial>, miiCard.Consumers.Service.v1.Financial.IFinancial {
        
        public FinancialClient() {
        }
        
        public FinancialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsRefreshInProgress() {
            return base.Channel.IsRefreshInProgress();
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsRefreshInProgressCreditCards() {
            return base.Channel.IsRefreshInProgressCreditCards();
        }
        
        public miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfFinancialRefreshStatus RefreshFinancialData() {
            return base.Channel.RefreshFinancialData();
        }
        
        public miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfFinancialRefreshStatus RefreshFinancialDataCreditCards() {
            return base.Channel.RefreshFinancialDataCreditCards();
        }
        
        public miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfMiiFinancialData GetFinancialTransactions() {
            return base.Channel.GetFinancialTransactions();
        }
        
        public miiCard.Consumers.Service.v1.Financial.MiiApiResponseOfMiiFinancialData GetFinancialTransactionsCreditCards() {
            return base.Channel.GetFinancialTransactionsCreditCards();
        }
    }
}
