//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miiCard.Consumers.Service.v1.Claims {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfMiiUserProfile", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfMiiUserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiUserProfile DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiUserProfile Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiUserProfile", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiUserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.EmailAddress[] EmailAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasPublicProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.Identity[] IdentitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdentityAssuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.PhoneNumber[] PhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.PostalAddress[] PostalAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileShortUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiUserProfile PublicProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.Qualification[] QualificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.WebProperty[] WebPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardImageUrl {
            get {
                return this.CardImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CardImageUrlField, value) != true)) {
                    this.CardImageUrlField = value;
                    this.RaisePropertyChanged("CardImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.EmailAddress[] EmailAddresses {
            get {
                return this.EmailAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressesField, value) != true)) {
                    this.EmailAddressesField = value;
                    this.RaisePropertyChanged("EmailAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasPublicProfile {
            get {
                return this.HasPublicProfileField;
            }
            set {
                if ((this.HasPublicProfileField.Equals(value) != true)) {
                    this.HasPublicProfileField = value;
                    this.RaisePropertyChanged("HasPublicProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.Identity[] Identities {
            get {
                return this.IdentitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentitiesField, value) != true)) {
                    this.IdentitiesField = value;
                    this.RaisePropertyChanged("Identities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IdentityAssured {
            get {
                return this.IdentityAssuredField;
            }
            set {
                if ((this.IdentityAssuredField.Equals(value) != true)) {
                    this.IdentityAssuredField = value;
                    this.RaisePropertyChanged("IdentityAssured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastVerified {
            get {
                return this.LastVerifiedField;
            }
            set {
                if ((this.LastVerifiedField.Equals(value) != true)) {
                    this.LastVerifiedField = value;
                    this.RaisePropertyChanged("LastVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.PhoneNumber[] PhoneNumbers {
            get {
                return this.PhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumbersField, value) != true)) {
                    this.PhoneNumbersField = value;
                    this.RaisePropertyChanged("PhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.PostalAddress[] PostalAddresses {
            get {
                return this.PostalAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressesField, value) != true)) {
                    this.PostalAddressesField = value;
                    this.RaisePropertyChanged("PostalAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousFirstName {
            get {
                return this.PreviousFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousFirstNameField, value) != true)) {
                    this.PreviousFirstNameField = value;
                    this.RaisePropertyChanged("PreviousFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousLastName {
            get {
                return this.PreviousLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousLastNameField, value) != true)) {
                    this.PreviousLastNameField = value;
                    this.RaisePropertyChanged("PreviousLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousMiddleName {
            get {
                return this.PreviousMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousMiddleNameField, value) != true)) {
                    this.PreviousMiddleNameField = value;
                    this.RaisePropertyChanged("PreviousMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileShortUrl {
            get {
                return this.ProfileShortUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileShortUrlField, value) != true)) {
                    this.ProfileShortUrlField = value;
                    this.RaisePropertyChanged("ProfileShortUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileUrl {
            get {
                return this.ProfileUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileUrlField, value) != true)) {
                    this.ProfileUrlField = value;
                    this.RaisePropertyChanged("ProfileUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiUserProfile PublicProfile {
            get {
                return this.PublicProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicProfileField, value) != true)) {
                    this.PublicProfileField = value;
                    this.RaisePropertyChanged("PublicProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.Qualification[] Qualifications {
            get {
                return this.QualificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationsField, value) != true)) {
                    this.QualificationsField = value;
                    this.RaisePropertyChanged("Qualifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.WebProperty[] WebProperties {
            get {
                return this.WebPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.WebPropertiesField, value) != true)) {
                    this.WebPropertiesField = value;
                    this.RaisePropertyChanged("WebProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiErrorCode", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    public enum MiiApiErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownSearchCriterion = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatches = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessRevoked = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserSubscriptionLapsed = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionalSupportDisabled = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FinancialDataSupportDisabled = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DevelopmentTransactionalSupportOnly = 1010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSnapshotId = 1020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blacklisted = 2000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductDisabled = 2010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductDeleted = 2020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 10000,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiCallStatus", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    public enum MiiApiCallStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddress", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class EmailAddress : miiCard.Consumers.Service.v1.Claims.Claim {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrimaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimary {
            get {
                return this.IsPrimaryField;
            }
            set {
                if ((this.IsPrimaryField.Equals(value) != true)) {
                    this.IsPrimaryField = value;
                    this.RaisePropertyChanged("IsPrimary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identity", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class Identity : miiCard.Consumers.Service.v1.Claims.Claim {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileUrl {
            get {
                return this.ProfileUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileUrlField, value) != true)) {
                    this.ProfileUrlField = value;
                    this.RaisePropertyChanged("ProfileUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class PhoneNumber : miiCard.Consumers.Service.v1.Claims.Claim {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMobile {
            get {
                return this.IsMobileField;
            }
            set {
                if ((this.IsMobileField.Equals(value) != true)) {
                    this.IsMobileField = value;
                    this.RaisePropertyChanged("IsMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimary {
            get {
                return this.IsPrimaryField;
            }
            set {
                if ((this.IsPrimaryField.Equals(value) != true)) {
                    this.IsPrimaryField = value;
                    this.RaisePropertyChanged("IsPrimary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalNumber {
            get {
                return this.NationalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalNumberField, value) != true)) {
                    this.NationalNumberField = value;
                    this.RaisePropertyChanged("NationalNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostalAddress", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class PostalAddress : miiCard.Consumers.Service.v1.Claims.Claim {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string House {
            get {
                return this.HouseField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseField, value) != true)) {
                    this.HouseField = value;
                    this.RaisePropertyChanged("House");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimary {
            get {
                return this.IsPrimaryField;
            }
            set {
                if ((this.IsPrimaryField.Equals(value) != true)) {
                    this.IsPrimaryField = value;
                    this.RaisePropertyChanged("IsPrimary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Qualification", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class Qualification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataProviderUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.QualificationType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProvider {
            get {
                return this.DataProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProviderField, value) != true)) {
                    this.DataProviderField = value;
                    this.RaisePropertyChanged("DataProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderUrl {
            get {
                return this.DataProviderUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProviderUrlField, value) != true)) {
                    this.DataProviderUrlField = value;
                    this.RaisePropertyChanged("DataProviderUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.QualificationType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebProperty", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class WebProperty : miiCard.Consumers.Service.v1.Claims.Claim {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.WebPropertyType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.WebPropertyType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Claim", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(miiCard.Consumers.Service.v1.Claims.Identity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(miiCard.Consumers.Service.v1.Claims.PhoneNumber))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(miiCard.Consumers.Service.v1.Claims.PostalAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(miiCard.Consumers.Service.v1.Claims.WebProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(miiCard.Consumers.Service.v1.Claims.EmailAddress))]
    public partial class Claim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified {
            get {
                return this.VerifiedField;
            }
            set {
                if ((this.VerifiedField.Equals(value) != true)) {
                    this.VerifiedField = value;
                    this.RaisePropertyChanged("Verified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebPropertyType", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    public enum WebPropertyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Domain = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Website = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QualificationType", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    public enum QualificationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Academic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Professional = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfArrayOfIdentitySnapshotDetails", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfArrayOfIdentitySnapshotDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.IdentitySnapshotDetails[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.IdentitySnapshotDetails[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentitySnapshotDetails", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Transactional")]
    [System.SerializableAttribute()]
    public partial class IdentitySnapshotDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnapshotIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasTestUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SnapshotId {
            get {
                return this.SnapshotIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SnapshotIdField, value) != true)) {
                    this.SnapshotIdField = value;
                    this.RaisePropertyChanged("SnapshotId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimestampUtc {
            get {
                return this.TimestampUtcField;
            }
            set {
                if ((this.TimestampUtcField.Equals(value) != true)) {
                    this.TimestampUtcField = value;
                    this.RaisePropertyChanged("TimestampUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasTestUser {
            get {
                return this.WasTestUserField;
            }
            set {
                if ((this.WasTestUserField.Equals(value) != true)) {
                    this.WasTestUserField = value;
                    this.RaisePropertyChanged("WasTestUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfIdentitySnapshot", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfIdentitySnapshot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.IdentitySnapshot DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.IdentitySnapshot Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentitySnapshot", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api.Transactional")]
    [System.SerializableAttribute()]
    public partial class IdentitySnapshot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.IdentitySnapshotDetails DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiUserProfile SnapshotField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.IdentitySnapshotDetails Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiUserProfile Snapshot {
            get {
                return this.SnapshotField;
            }
            set {
                if ((object.ReferenceEquals(this.SnapshotField, value) != true)) {
                    this.SnapshotField = value;
                    this.RaisePropertyChanged("Snapshot");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardImageConfiguration", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class CardImageConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnapshotIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowEmailAddress {
            get {
                return this.ShowEmailAddressField;
            }
            set {
                if ((this.ShowEmailAddressField.Equals(value) != true)) {
                    this.ShowEmailAddressField = value;
                    this.RaisePropertyChanged("ShowEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowPhoneNumber {
            get {
                return this.ShowPhoneNumberField;
            }
            set {
                if ((this.ShowPhoneNumberField.Equals(value) != true)) {
                    this.ShowPhoneNumberField = value;
                    this.RaisePropertyChanged("ShowPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SnapshotId {
            get {
                return this.SnapshotIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SnapshotIdField, value) != true)) {
                    this.SnapshotIdField = value;
                    this.RaisePropertyChanged("SnapshotId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MiiApiResponseOfAuthenticationDetails", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class MiiApiResponseOfAuthenticationDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.AuthenticationDetails DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.AuthenticationDetails Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTestUser {
            get {
                return this.IsTestUserField;
            }
            set {
                if ((this.IsTestUserField.Equals(value) != true)) {
                    this.IsTestUserField = value;
                    this.RaisePropertyChanged("IsTestUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.MiiApiCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationDetails", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class AuthenticationDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AuthenticationTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.GeographicLocation[] LocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondFactorProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.AuthenticationTokenType SecondFactorTokenTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AuthenticationTimeUtc {
            get {
                return this.AuthenticationTimeUtcField;
            }
            set {
                if ((this.AuthenticationTimeUtcField.Equals(value) != true)) {
                    this.AuthenticationTimeUtcField = value;
                    this.RaisePropertyChanged("AuthenticationTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.GeographicLocation[] Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondFactorProvider {
            get {
                return this.SecondFactorProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondFactorProviderField, value) != true)) {
                    this.SecondFactorProviderField = value;
                    this.RaisePropertyChanged("SecondFactorProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.AuthenticationTokenType SecondFactorTokenType {
            get {
                return this.SecondFactorTokenTypeField;
            }
            set {
                if ((this.SecondFactorTokenTypeField.Equals(value) != true)) {
                    this.SecondFactorTokenTypeField = value;
                    this.RaisePropertyChanged("SecondFactorTokenType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeographicLocation", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    [System.SerializableAttribute()]
    public partial class GeographicLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private miiCard.Consumers.Service.v1.Claims.PostalAddress ApproximateAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LatLongAccuracyMetresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public miiCard.Consumers.Service.v1.Claims.PostalAddress ApproximateAddress {
            get {
                return this.ApproximateAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ApproximateAddressField, value) != true)) {
                    this.ApproximateAddressField = value;
                    this.RaisePropertyChanged("ApproximateAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LatLongAccuracyMetres {
            get {
                return this.LatLongAccuracyMetresField;
            }
            set {
                if ((this.LatLongAccuracyMetresField.Equals(value) != true)) {
                    this.LatLongAccuracyMetresField = value;
                    this.RaisePropertyChanged("LatLongAccuracyMetres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationProvider {
            get {
                return this.LocationProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationProviderField, value) != true)) {
                    this.LocationProviderField = value;
                    this.RaisePropertyChanged("LocationProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationTokenType", Namespace="http://schemas.datacontract.org/2004/07/miiCard.STS.Model.Api")]
    public enum AuthenticationTokenType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Soft = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hard = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="v1.Claims.IClaims")]
    public interface IClaims {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetClaims", ReplyAction="http://tempuri.org/IClaims/GetClaimsResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfMiiUserProfile GetClaims();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/AssuranceImage", ReplyAction="http://tempuri.org/IClaims/AssuranceImageResponse")]
        System.IO.Stream AssuranceImage(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/IsSocialAccountAssured", ReplyAction="http://tempuri.org/IClaims/IsSocialAccountAssuredResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsSocialAccountAssured(string socialAccountId, string socialAccountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/IsUserAssured", ReplyAction="http://tempuri.org/IClaims/IsUserAssuredResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsUserAssured();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetIdentitySnapshotDetails", ReplyAction="http://tempuri.org/IClaims/GetIdentitySnapshotDetailsResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfArrayOfIdentitySnapshotDetails GetIdentitySnapshotDetails(string snapshotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetIdentitySnapshot", ReplyAction="http://tempuri.org/IClaims/GetIdentitySnapshotResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfIdentitySnapshot GetIdentitySnapshot(string snapshotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetIdentitySnapshotPdf", ReplyAction="http://tempuri.org/IClaims/GetIdentitySnapshotPdfResponse")]
        System.IO.Stream GetIdentitySnapshotPdf(string snapshotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetCardImage", ReplyAction="http://tempuri.org/IClaims/GetCardImageResponse")]
        System.IO.Stream GetCardImage(miiCard.Consumers.Service.v1.Claims.CardImageConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaims/GetAuthenticationDetails", ReplyAction="http://tempuri.org/IClaims/GetAuthenticationDetailsResponse")]
        miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfAuthenticationDetails GetAuthenticationDetails(string snapshotId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClaimsChannel : miiCard.Consumers.Service.v1.Claims.IClaims, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClaimsClient : System.ServiceModel.ClientBase<miiCard.Consumers.Service.v1.Claims.IClaims>, miiCard.Consumers.Service.v1.Claims.IClaims {
        
        public ClaimsClient() {
        }
        
        public ClaimsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfMiiUserProfile GetClaims() {
            return base.Channel.GetClaims();
        }
        
        public System.IO.Stream AssuranceImage(string type) {
            return base.Channel.AssuranceImage(type);
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsSocialAccountAssured(string socialAccountId, string socialAccountType) {
            return base.Channel.IsSocialAccountAssured(socialAccountId, socialAccountType);
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfboolean IsUserAssured() {
            return base.Channel.IsUserAssured();
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfArrayOfIdentitySnapshotDetails GetIdentitySnapshotDetails(string snapshotId) {
            return base.Channel.GetIdentitySnapshotDetails(snapshotId);
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfIdentitySnapshot GetIdentitySnapshot(string snapshotId) {
            return base.Channel.GetIdentitySnapshot(snapshotId);
        }
        
        public System.IO.Stream GetIdentitySnapshotPdf(string snapshotId) {
            return base.Channel.GetIdentitySnapshotPdf(snapshotId);
        }
        
        public System.IO.Stream GetCardImage(miiCard.Consumers.Service.v1.Claims.CardImageConfiguration configuration) {
            return base.Channel.GetCardImage(configuration);
        }
        
        public miiCard.Consumers.Service.v1.Claims.MiiApiResponseOfAuthenticationDetails GetAuthenticationDetails(string snapshotId) {
            return base.Channel.GetAuthenticationDetails(snapshotId);
        }
    }
}
